# SPDX-License-Identifier: MIT
# Copyright (c) 2026 Simon Morley / NullRabbit
"""Bundle contract v1 — the canonical on-disk shape of a training-run.

A **bundle** is a single directory containing the complete trace
of one attack (or benign) run against a validator lab:

```
<corpus_id>/
├── manifest.json       — BundleManifest (this module)
├── packets.pcap        — raw packet capture, snaplen-256 default
├── host.parquet        — host time-series (host_ts_schema)
├── app.parquet         — application / Prometheus time-series
├── protocol.parquet    — consensus / protocol time-series
└── responses.parquet   — per-request response semantics
```

All four Parquet files carry a monotonic ``t_ns`` column referenced
to the same ``started_at`` in the manifest. Joining across modalities
is a simple merge-asof.

Bundle schema is versioned. Backward compat rules:

- Adding a new *optional* manifest field → bump minor, don't bump
  BUNDLE_VERSION. Old consumers ignore unknown fields.
- Adding a new *required* manifest field or Parquet column →
  bump BUNDLE_VERSION, ship new module ``bundle_v2``.
- Removing or re-typing a field → bump BUNDLE_VERSION, ship new
  module.
"""

from __future__ import annotations

import hashlib
import json
from datetime import datetime
from enum import Enum
from typing import Any, Literal

import pyarrow as pa
from pydantic import BaseModel, ConfigDict, Field, field_validator, model_validator

from bundle_spec.taxonomy import FamilyId

BUNDLE_VERSION = 1


class Posture(str, Enum):
    """Canonical posture taxonomy.

    The first eight values cover the attack-side posture axis (rate /
    obfuscation / source-distribution variants of the attack). The
    four ``*_normal`` values are benign-side organic-client postures:

    - ``wallet_normal`` — single-user wallet UI workload (5–15 s polls)
    - ``indexer_normal`` — backfilling indexer (0.1–0.5 s polls/worker)
    - ``light_client_normal`` — light client / health-check (30–120 s polls)
    - ``mixed_normal`` — weighted mix of the above (50/30/20)

    Attack reproducers don't use the ``*_normal`` postures; benign
    reproducer-pipeline bundles don't use the attack-side eight.

    The trailing four values are high-load benign postures driving
    the validator into operational regimes that overlap attack
    distributions on system-resource metrics — used to test that a
    detector distinguishes attack-shape from benign-load-shape.
    """

    saturating = "saturating"
    low_volume = "low-volume"
    distributed = "distributed"
    mimicry = "mimicry"
    insider = "insider"
    validator_compromised = "validator-compromised"
    reconnaissance = "reconnaissance"
    historical_cve = "historical-cve"
    wallet_normal = "wallet_normal"
    indexer_normal = "indexer_normal"
    light_client_normal = "light_client_normal"
    mixed_normal = "mixed_normal"
    dex_swap_burst = "dex_swap_burst"
    nft_mint_storm = "nft_mint_storm"
    indexer_backfill = "indexer_backfill"
    mixed_high_load = "mixed_high_load"


class GroundTruthLabel(str, Enum):
    attack = "attack"
    benign = "benign"
    suspicious = "suspicious"


class TrafficSource(str, Enum):
    """How the captured traffic was produced.

    - ``synthetic-client``: traffic was generated by the bundle
      producer itself and captured passively (no per-RPC
      ``record_response`` calls — the ``responses.parquet`` modality
      is unpopulated). Lightweight benign-capture pipeline.
    - ``mainnet-organic``: captured from a mainnet-synced fullnode
      serving real clients; traffic source is third parties.
    - ``mixed``: a mix of the above (e.g. mainnet fullnode with
      some synthetic probes interleaved).
    - ``reproducer-attack``: the traffic is the attack itself,
      driven by a reproducer. The "source" is the adversarial
      harness, not a legitimate client. ``record_response`` is
      called per RPC; ``responses.parquet`` is populated.
    - ``reproducer-benign``: synthetic clients producing benign
      traffic, captured through the **same reproducer pipeline as
      reproducer-attack** (``record_response`` populated, host +
      app monitored). Distinct from ``synthetic-client`` so dataset
      curators can pair benign-bundles with the same modality-
      population shape as attack-bundles when training a
      capture-pipeline-co-linearity-aware detector.
    - ``validator-under-load``: high-load legitimate workloads
      driving the validator into operational regimes overlapping
      attack distributions on system metrics. Distinct from
      ``reproducer-benign`` so leave-one-stratum-out holdout treats
      it as a separate stratum.
    """

    synthetic_client = "synthetic-client"
    mainnet_organic = "mainnet-organic"
    mixed = "mixed"
    reproducer_attack = "reproducer-attack"
    reproducer_benign = "reproducer-benign"
    validator_under_load = "validator-under-load"


class FidelityClass(str, Enum):
    """How faithfully the bundle reproduces the real attack on the wire.

    - ``stub``: placeholder reproducer with hand-crafted or test-
      vector-derived input. Shape-only; semantic parity with a real
      attack is not claimed.
    - ``proxy``: wire shape reproduced via a substitute mechanism
      that approximates but doesn't natively produce the attack
      (e.g. a TCP-flood proxy approximating a custom-protocol flood).
    - ``lab``: full reproducer producing genuine attack traffic in a
      controlled lab environment (localnet / private testnet).
    - ``lab-tls-fronted``: full reproducer producing genuine attack
      traffic against a TLS-terminating proxy (nginx) in front of a
      localnet validator, captured at two vantage points:
      pre-termination wire (TLS frames; cipher-agnostic feature
      surface) and post-termination loopback (cleartext;
      full-feature surface).
    - ``production-captured``: sample directly captured from
      production-deployed adversarial tooling. Reserved for future
      production-ingest pipelines; no bundles in the v0.1.0
      reference corpus carry this value.
    - ``production-derived``: lab reproduction parametrised by
      patterns observed in production deployment. Bridges lab
      fidelity with in-field ground truth. Reserved for future use.

    Future-decomposition notice: this enum may be replaced or
    complemented in v0.2.0 with a structured pair of fields
    (``provenance.substrate`` × ``provenance.traffic_origin``);
    the change will be additive (existing readers stay compatible).
    """

    stub = "stub"
    proxy = "proxy"
    lab = "lab"
    lab_tls_fronted = "lab-tls-fronted"
    production_captured = "production-captured"
    production_derived = "production-derived"


class TargetAuthorisation(str, Enum):
    """Authorisation scope for the target that was captured.

    Gates every downstream publication decision. A bundle with
    ``target_authorisation`` other than ``self-owned`` / ``synthetic``
    requires deliberate review before ever being published — the
    publication pipeline filters on this.

    - ``self-owned``: capture against operator-owned infrastructure
      (test validators, owned fullnodes, internal localnet).
    - ``customer-authorised``: capture against third-party
      infrastructure under explicit written authorisation (paid
      engagement, signed scope-of-work). Requires the optional
      ``engagement_id`` provenance field to be populated with the
      engagement record's opaque identifier.
    - ``public-mainnet-passive``: passive capture of public mainnet
      traffic from a fullnode under the operator's own control,
      observing organic third-party clients.
    - ``synthetic``: capture against entirely synthetic targets with
      no real validator software. Rare, unit-test fixtures only.
    """

    self_owned = "self-owned"
    customer_authorised = "customer-authorised"
    public_mainnet_passive = "public-mainnet-passive"
    synthetic = "synthetic"


class Provenance(BaseModel):
    """Bundle-production provenance. ``traffic_source``,
    ``fidelity_class``, and ``target_authorisation`` are required so
    every bundle carries unambiguous structured labels for downstream
    dataset curation.

    Other provenance fields are free-form extras (``extra="allow"``)
    to keep room for per-recorder debugging info (return codes,
    process IDs, capture-module versions, ...) without schema churn.
    """

    model_config = ConfigDict(extra="allow")

    traffic_source: TrafficSource = Field(
        description=(
            "Required. synthetic-client / mainnet-organic / mixed / "
            "reproducer-attack / reproducer-benign / validator-under-load. "
            "See TrafficSource docstring."
        ),
    )

    fidelity_class: FidelityClass = Field(
        description=(
            "How faithfully the bundle reproduces the real attack on "
            "the wire. stub / proxy / lab / lab-tls-fronted / "
            "production-captured / production-derived. Required — "
            "every bundle must declare fidelity."
        ),
    )

    target_authorisation: TargetAuthorisation = Field(
        description=(
            "Authorisation scope for the target. Required — gates "
            "publication downstream."
        ),
    )

    engagement_id: str | None = Field(
        default=None,
        description=(
            "Opaque identifier referencing the customer engagement "
            "record. Required only when "
            "target_authorisation == customer-authorised. Null for "
            "self-owned / synthetic / public-mainnet-passive."
        ),
    )

    tooling: dict[str, str] = Field(
        default_factory=dict,
        description=(
            "Structured tool-version log: {tool_name: version} "
            "captured at bundle-produce time so downstream "
            "consumers know exactly which tooling produced the "
            "bundle. Required to be non-empty for "
            "family_id=reconnaissance bundles (off-the-shelf "
            "tooling drift between versions changes request "
            "shape — version pinning is load-bearing). Optional "
            "for other families but reproducers are encouraged "
            "to populate it."
        ),
    )

    pcap_path_pre_termination: str | None = Field(
        default=None,
        description=(
            "Optional. Path to a secondary pcap captured at the "
            "pre-termination wire vantage when the bundle was "
            "captured behind a TLS-terminating proxy "
            "(fidelity_class=lab-tls-fronted dual-vantage capture). "
            "When set, the primary pcap.pcap is the post-"
            "termination loopback (cleartext, full feature surface) "
            "and this field references the pre-termination wire "
            "(TLS frames, cipher-agnostic feature surface). Null "
            "for single-vantage captures."
        ),
    )

    @model_validator(mode="after")
    def _engagement_id_required_for_customer(self) -> "Provenance":
        """A customer-authorised capture must reference an engagement
        record — otherwise the bundle has no audit trail back to the
        authorisation. Enforced here rather than at publication time
        so the gap surfaces at produce-time, not later."""
        if (
            self.target_authorisation is TargetAuthorisation.customer_authorised
            and not self.engagement_id
        ):
            raise ValueError(
                "engagement_id is required when "
                "target_authorisation='customer-authorised'"
            )
        return self


class BundleFiles(BaseModel):
    """Which on-disk modalities the bundle considers schema-conformant.

    Semantics (forward-only contract):

    - ``True``: the named file MUST be present in the bundle directory
      and is conformant with the modality's schema. Consumers should
      read it.
    - ``False``: the modality is NOT considered conformant for this
      bundle. The file MAY OR MAY NOT exist on disk; if it does, it is
      typically an empty placeholder (e.g. zero-row Parquet) or a
      non-conformant capture that the producer didn't include in the
      bundle's effective modality set. Consumers SHOULD NOT read it.

    This asymmetric semantic exists because the reference example
    bundles (and many producers' captures) ship empty placeholders for
    modalities that didn't capture during a workload — for instance a
    passive-fullnode benign bundle has no RPC traffic to serve, so
    ``responses.parquet`` exists as an empty placeholder but
    ``responses_parquet=False``. Validators should enforce the forward
    direction only (``True`` ⇒ file present); reverse-checking
    ``False`` ⇒ file absent breaks against the existing example
    convention. The validator at ``tools/validate_bundle.py``
    implements the forward-only check.

    ``vectors_parquet`` is a sixth modality slot reserved for
    behavioural / fingerprint vectors that don't fit the other four
    modalities (e.g. timing-resonance signatures, derived behavioural
    embeddings). Currently unpopulated in the v0.1.0 reference corpus;
    the schema slot is reserved.
    """

    packets_pcap: bool = True
    host_parquet: bool = False
    app_parquet: bool = False
    protocol_parquet: bool = False
    responses_parquet: bool = False
    vectors_parquet: bool = False


def compute_genome_id(attack_parameters: dict[str, Any]) -> str:
    """Deterministic genome id for a set of attack parameters.

    SHA-256 of the JSON-serialised attack_parameters with sorted
    keys, truncated to the first 16 hex characters. Pure function:
    identical parameters always hash to the same genome_id, so
    lineage tracking is deterministic.

    Rules (canonicalisation contract — REQUIRED for cross-language
    parser implementations to produce the same genome_id):

    - Keys are sorted to stabilise across insertion order.
    - ``default=str`` handles non-JSON types (datetimes, Paths,
      Enums) by stringifying. Keep attack_parameters to JSON-safe
      values to avoid surprises across languages.
    - Output is ASCII (UTF-8 of an ASCII-only JSON serialisation).
    - SHA-256 over the canonical UTF-8 byte sequence.
    - First 16 lowercase hex characters of the digest.

    Cross-language parsers (e.g. the Rust reference parser at
    ``rust/bundle_spec/genome_id.rs``) must produce identical output
    for identical input under this canonicalisation. A determinism
    pin test in ``tests/test_genome_id.py`` enforces this.
    """
    canonical = json.dumps(attack_parameters, sort_keys=True, default=str)
    return hashlib.sha256(canonical.encode("utf-8")).hexdigest()[:16]


class BundleManifest(BaseModel):
    """Top-level manifest for one run."""

    model_config = ConfigDict(extra="forbid", frozen=False)

    bundle_version: int = Field(default=BUNDLE_VERSION)
    shape: Literal["v0.0", "v1.0"] = Field(
        description="v0.0 = pcap-only (legacy ingest). v1.0 = full multi-modal.",
    )

    # Identity
    corpus_id: str = Field(description="Globally unique bundle id.")
    attack_id: str
    genome_id: str | None = Field(
        default=None,
        description=(
            "Deterministic hash of attack_parameters (see compute_genome_id). "
            "Nullable at the schema level because some bundles legitimately "
            "don't have one (e.g. passive-recorder captures). Required for "
            "attack bundles: a model validator asserts genome_id is non-null "
            "when ground_truth_label == 'attack'."
        ),
    )
    assessment_id: str | None = None

    # Taxonomy — two-level.
    family_id: FamilyId = Field(
        description=(
            "Chain-agnostic vulnerability-class label "
            "(see bundle_spec.taxonomy.FamilyId)."
        ),
    )
    primitive_id: str = Field(
        description=(
            "Chain-specific implementation of a family, e.g. "
            "'sui_F10_multi_get_objects_amp' under family_id='response_amp'."
        ),
    )
    posture: Posture
    ground_truth_label: GroundTruthLabel
    chain: str = Field(
        description="'sui' | 'solana' | 'cosmos' | 'ethereum' | 'cross-chain'. Required from v1.0.",
    )

    # Run metadata
    run_tag: str = Field(description="Mutator-chosen label for this specific parametrisation.")
    target_env: str = Field(
        description="Canonical env name, e.g. 'localnet-sui-multinode4', 'docker-misconfig-compose'.",
    )
    generation_method: Literal[
        "hand",
        "rules_v0",
        "llm_v0",
        "production_review",
        "backfill_v0",
    ] = "hand"

    # Time window — both required, same clock (host CLOCK_REALTIME).
    started_at: datetime
    ended_at: datetime

    # Free-form, validated per-primitive by the primitive descriptor.
    attack_parameters: dict[str, Any] = Field(default_factory=dict)

    # Optional: what the detector *should* see.
    expected_detection_signature: dict[str, Any] | None = None

    # Which files are on disk.
    files: BundleFiles = Field(default_factory=BundleFiles)

    # Provenance — traffic_source is required; extras allowed.
    provenance: Provenance
    notes: str | None = None

    @field_validator("corpus_id", "attack_id", "primitive_id", "run_tag", "target_env", "chain")
    @classmethod
    def _nonempty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("must be a non-empty string")
        return v

    @field_validator("ended_at")
    @classmethod
    def _time_order(cls, v: datetime, info: Any) -> datetime:
        started = info.data.get("started_at")
        if started is not None and v < started:
            raise ValueError("ended_at must be >= started_at")
        return v

    @model_validator(mode="after")
    def _attack_requires_genome_id(self) -> "BundleManifest":
        """Contract: attack bundles must carry a genome_id for mutator
        lineage + dedup. Benign bundles may skip it — there's no
        attack_parameters lineage to track."""
        if self.ground_truth_label is GroundTruthLabel.attack and not self.genome_id:
            raise ValueError(
                "genome_id is required for bundles with ground_truth_label='attack'. "
                "Use compute_genome_id(attack_parameters) to derive it."
            )
        return self

    @model_validator(mode="after")
    def _reconnaissance_requires_tooling(self) -> "BundleManifest":
        """Contract: reconnaissance bundles must declare which
        off-the-shelf tooling produced them. Tool-version drift
        between e.g. nmap 7.x and 8.x changes request shapes
        materially; without a structured version log, downstream
        consumers can't tell whether two bundles' shapes diverge
        because of attack parameter change or because the tooling
        moved underneath them."""
        if (
            self.family_id is FamilyId.reconnaissance
            and not self.provenance.tooling
        ):
            raise ValueError(
                "provenance.tooling is required (non-empty) for "
                "bundles with family_id='reconnaissance'. Populate "
                "with {tool_name: version} pairs at produce-time."
            )
        return self


# ─── Time-series Parquet schemas ─────────────────────────────────────────
#
# Every time-series file has a monotonic `t_ns` column — nanoseconds
# since the manifest's `started_at`. That's the join key across
# modalities. All other columns are float64 or int64 (nullable) to
# keep Arrow → pandas → numpy round-trip cheap.
#
# Cross-language consistency: the equivalent Rust crate exposes the
# same schemas as `arrow_schema::Schema` constants. CI verifies
# byte-for-byte equivalence; see ``tools/compare_arrow_schemas.py``.


def host_ts_schema() -> pa.Schema:
    """Host-level telemetry, ~100 ms resolution, from psutil or equiv.

    Captured on the validator host for the duration of the run.
    Columns may be null if a given signal isn't available on the
    platform (e.g. io_read_bytes on macOS).
    """
    return pa.schema(
        [
            pa.field("t_ns", pa.int64(), nullable=False),
            pa.field("pid", pa.int32(), nullable=True),
            pa.field("rss_bytes", pa.int64(), nullable=True),
            pa.field("vms_bytes", pa.int64(), nullable=True),
            pa.field("cpu_pct", pa.float32(), nullable=True),
            pa.field("num_fds", pa.int32(), nullable=True),
            pa.field("num_threads", pa.int32(), nullable=True),
            pa.field("num_connections", pa.int32(), nullable=True),
            pa.field("io_read_bytes", pa.int64(), nullable=True),
            pa.field("io_write_bytes", pa.int64(), nullable=True),
            pa.field("ctx_switches_voluntary", pa.int64(), nullable=True),
            pa.field("ctx_switches_involuntary", pa.int64(), nullable=True),
        ]
    )


def app_ts_schema() -> pa.Schema:
    """Application metrics — wide-table Prometheus scrape samples.

    Each row = one scrape. ``metric_name`` + ``labels_json`` uniquely
    identify the series; ``value`` is the observed float. Long
    format keeps the schema stable as primitives add/remove metrics.
    """
    return pa.schema(
        [
            pa.field("t_ns", pa.int64(), nullable=False),
            pa.field("metric_name", pa.string(), nullable=False),
            pa.field("labels_json", pa.string(), nullable=False),
            pa.field("value", pa.float64(), nullable=False),
        ]
    )


def protocol_ts_schema() -> pa.Schema:
    """Protocol / consensus signals, chain-agnostic where possible.

    ``signal`` is an enumerated string (checkpoint_height,
    committed_round, queue_depth, peer_count, …). New signals may
    be added without a schema bump — readers must tolerate unknown
    ``signal`` values.
    """
    return pa.schema(
        [
            pa.field("t_ns", pa.int64(), nullable=False),
            pa.field("signal", pa.string(), nullable=False),
            pa.field("value", pa.float64(), nullable=True),
            pa.field("value_str", pa.string(), nullable=True),
        ]
    )


def responses_schema() -> pa.Schema:
    """Per-request response semantics.

    One row per application-level request observed in the capture.
    ``response_class`` is a coarse tag filled by primitive-specific
    post-processing (e.g. 'framework_package_bcs_blob', 'wallet_rpc',
    'error_json').
    """
    return pa.schema(
        [
            pa.field("t_ns", pa.int64(), nullable=False),
            pa.field("endpoint", pa.string(), nullable=False),
            pa.field("request_size_bytes", pa.int64(), nullable=True),
            pa.field("response_size_bytes", pa.int64(), nullable=True),
            pa.field("status_code", pa.int32(), nullable=True),
            pa.field("response_class", pa.string(), nullable=True),
            pa.field("duration_ns", pa.int64(), nullable=True),
        ]
    )


def vectors_schema() -> pa.Schema:
    """Behavioural / fingerprint vectors captured alongside the
    trace. One row per vector.

    Intended use cases that don't fit the other modalities:

    - Timing-resonance signatures from network sensors on the wire
      (pre-deployment reconnaissance fingerprints).
    - Derived behavioural embeddings (client-family classification,
      probe-response signatures).
    - Tool-specific output that has a natural vector representation
      but isn't a time-series or a per-request row.

    ``vector_kind`` is an open string taxonomy (consumers tolerate
    unknown kinds). ``source_id`` uniquely identifies the producing
    tool + version for lineage. ``metadata_json`` carries tool-
    specific structured extras without schema churn.

    Currently unpopulated in the v0.1.0 reference corpus. The slot
    is reserved as part of the v1.0 contract.
    """
    return pa.schema(
        [
            pa.field("t_ns", pa.int64(), nullable=False),
            pa.field("vector_kind", pa.string(), nullable=False),
            pa.field("vector_dim", pa.int32(), nullable=False),
            pa.field("vector_data", pa.list_(pa.float32()), nullable=False),
            pa.field("source_id", pa.string(), nullable=False),
            pa.field("metadata_json", pa.string(), nullable=True),
        ]
    )
